# -*- coding: utf-8 -*-
"""CSE303_LAB01_2018260133.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuQ80Vpz7L4ZfMhV-LwO9yXPWs3qWl7O

**Problem-01**
"""

num1= int(input("Enter the first number: "))
num2= int(input("Enter the second number: "))
r=int(num1*num2)
print(r)
if r>1000:
  sum=num1+num2
  print(sum)

"""**Problem-02**"""

r=int(input("Enter the Radius of the Circle: "))
A=3.1416*r
print(A)
C=2*3.1416*r
print(C)

"""**Problem-03**"""

def compound_interest_2018_2_60_133(P,R,T):
   A=P*(pow((1+R/100),T))
   return A
P=float(input("Enter the Principle Amount: "))
R=float(input("Enter the Interest Rate: "))
T=int(input("Enter the Time: "))
A=compound_interest_2018_2_60_133(P,R,T)
print("Compound Interest is %.1f" % A);

"""**Problem-04**"""

N=int(input("Enter Any Positive Integer: "))
S=0
S= (N*(N+1)*(2*N+1))/6
print("The Sum of the Series is %d" % S)

"""**Problem-05**"""

def prime_find_2018_2_60_133(n):
 if n>1:
   for i in range(2,n):
     if(n%i==0):
       print(n,"Is not a prime number")
       break
   else:
          print(n,"Is a prime number")
 else:
            print(n,"Is not a prime number")
n = int(input("Enter an input number:"))
prime_find_2018_2_60_133(n)

"""**Problem-06**"""

def Fibonacci(n):
  if n<=0:
    print("Invalid")
  elif n==1:
    return 0
  elif n==2:
    return 1
  else:
    return Fibonacci(n-1)+Fibonacci(n-2)
n= int(input("Enter the Value: "))
(Fibonacci(n))

"""**Problem-07**"""

def sum_of_list(x):
  result = 0
  for i in x:
    result = result + i
  return result

l = [1,2,3,4,15,16,17]
print ("The sum of the list is", sum_of_list(l))

"""**Problem-08**"""

l= [1,2,3,4,15,16,17]
result=0
for i in range(0,len(l)):
    if i % 2 == 0:
     result=result+l[i]
    else:
      pass
print(result)

"""**Problem-09**"""

def largest_number_2018_2_60_133(l):
    max = l[0]
    for x in l:
        if x > max :
             max = x
    return max
l = [2,4,6,10,65,12,16]
print("Largest element is:", largest_number_2018_2_60_133(l))
def smallest_number_2018_2_60_133(l):
    min = l[0]
    for x in l:
        if x < min :
             min = x
    return min
l = [2,4,6,10,65,12,16]
print("Smallest element is:", smallest_number_2018_2_60_133(l))

"""**Problem-10**"""

l=[10,3,4,34,6,67]
l.sort()
print("The Second largest number is:",l[-2])

"""**Problem-11**"""

string=input("Enter a string: ")
new_str=string[::2]
print(new_str)

"""**Problem-12**"""

s=input("Enter any String: ")
n=int(input("Enter any number: "))
new_str=s[:n]
print(new_str)

"""**Problem-13**"""

s = "The title of the course CSE303 is Statistics and Probability"
sub_str = "CSE303"
c=s.count(sub_str)
print("The count is:", c)

"""**Problem-14**"""

def palindrome_checker_2018_2_60_133(x):
 x = "madam"
w = ""
for i in x:
    w = i + w
if (x == w):
    print("Yes")
else:
    print("No")
palindrome_checker_2018_2_60_133(x)

"""**Problem-15**"""

l1=[5,4,8,9,12,13,22]
l2=[3,11,8,9,7,15,17,19]
x=[]
y=[]
n=len(l1)
for i in range (0,n,1):
    if(l1[i]%2==0):
        x.append(l1[i])
    if(l2[i]%2==1):
        y.append(l2[i])
print(x)
print(y)