# -*- coding: utf-8 -*-
"""Tasnia_2018260133_LAB02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O2MM5Hqk5wENKaN9j7V5OYfTSs69Y98H

**Problem-01**
"""

n1=[i for i in range(1,1001)]
result1=[n1 for n1 in n1 if n1%8==0]
print(result1)

"""**Problem-02**"""

n2=[i for i in range(1,1001)]
result2=[n2 for n2 in n2 if"6" in str(n2)]
print(result2)

"""**Problem-03**"""

s3= "Practice Problems to Drill List Comprehension in Your Head."
result3=len([c for c in s3 if c==" "])
print(result3)

"""**Problem-04**"""

s4= "Practice Problems to Drill List Comprehension in Your Head."
result4="".join([c for c in s4 if c not in["a","e","i","o","u"]])
print(result4)

"""**Problem-05**"""

s5 = "Practice Problems to Drill List Comprehension in Your Head."

examine = s5.split()

result5 = [word for word in examine if len(word) < 5]
print(result5)

"""**Problem-06**"""

s6 = "Practice Problems to Drill List Comprehension in Your Head."
result6={s6:len(s6)for s6 in s6}
print(result6)

"""**Problem-07**"""

n7=[i for i in range(1,1001)]
result7=[n7 for n7 in n7 if True in[True for d7 in range(2,9)if n7%d7==0]]
print(result7)

"""**Problem-08**"""

n8=[i for i in range(1,1001)]
result8={n:max([d8 for d8 in range(1,10) if n % d8 == 0]) for n in n8}
print(result8)